title: Verschwörhaus bleibt
description: Offener Brief an die Stadtverwaltung Ulm

# Set this to your domain; baseurl is for the folder in your domain, if you have one -- `blog`.
# you can leave both of them blank if you are deploying on a top-level domain.
url: https://itrich.github.io/vsh-bleibt
baseurl: /vsh-bleibt

# footer
footer:
  credit: false
  custom: true

# if above footer:custom is 'true', then this will be printed instead
footer_custom: 'Der Text dieses Briefes wurde unter CC BY-SA veröffentlicht.'

layout:
  theme: default # default, vintage, nord
  theme_switch: true # enable or disable user toggle switch between light and dark theme
  link_new_tab: true # should external links open in a new tab (true) or in the current tab (false)

# styles
# include only the styles you want [true | false]
styles:
  font_family: sans # serif, sans (default)
  forms: true

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

sass:
  sass_dir: /assets/css/_sass
  style: compressed # nested, compact, expanded or compressed
  sourcemap: never

plugins:
 - jekyll-optional-front-matter # https://github.com/benbalter/jekyll-optional-front-matter
 - jekyll-titles-from-headings # https://github.com/benbalter/jekyll-titles-from-headings/

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - netlify.toml
  - node_modules/
  - oinam-jekyll-*.*
  - oinam-jekyll.gemspec
  - README.*
  - server
  - vendor/
  - .sass-cache/